server:
  port: 8084
spring:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            application-id: kafka-stream-demo
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
          bindings:
            processedEventIn:
              producer:
                application-id: processed-event-stream
        binder:
          brokers: localhost:9092
      bindings:
        processedEventIn:
          destination: processedEvent
          group: processedEventGroup